package common.BankServerInterfacePackage;


/**
* common/BankServerInterfacePackage/invalid_client.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bankserver.idl
* Monday, October 30, 2017 12:24:52 AM EDT
*/

public final class invalid_client extends org.omg.CORBA.UserException
{

  public invalid_client ()
  {
    super(invalid_clientHelper.id());
  } // ctor


  public invalid_client (String $reason)
  {
    super(invalid_clientHelper.id() + "  " + $reason);
  } // ctor

} // class invalid_client
