package common;


/**
* common/BankServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bankserver.idl
* Tuesday, October 31, 2017 11:43:13 PM EDT
*/


//Interface for the Banking Server
public interface BankServerInterfaceOperations 
{
  int getLocalAccountCount ();
  String[] getAllCustomerAccount ();
  boolean createAccount (String firstName, String lastName, String address, String phone, String customerID, common.BranchID branchID) throws common.BankServerInterfacePackage.invalid_client;
  boolean editRecord (String customerID, common.EditRecordFields fieldName, String newValue) throws common.BankServerInterfacePackage.invalid_client;
  void deposit (String customerID, float amount) throws common.BankServerInterfacePackage.invalid_client, common.BankServerInterfacePackage.invalid_bankOperation;
  void withdraw (String customerID, float amount) throws common.BankServerInterfacePackage.invalid_client, common.BankServerInterfacePackage.invalid_bankOperation;
  void getBalance (String customerID) throws common.BankServerInterfacePackage.invalid_client;
  boolean transferFund (String sourceID, float amount, String destID) throws common.BankServerInterfacePackage.invalid_client, common.BankServerInterfacePackage.invalid_bankOperation;
  int getUDPPort ();
  String getUDPHost ();
  void shutdown ();
} // interface BankServerInterfaceOperations
