package common;


/**
* common/BankServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bankserver.idl
* Monday, October 30, 2017 12:24:52 AM EDT
*/

public interface BankServerInterface extends BankServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BankServerInterface
