package common;

/**
* common/BankServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bankserver.idl
* Wednesday, November 1, 2017 2:24:31 PM EDT
*/


//Interface for the Banking Server
public final class BankServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public common.BankServerInterface value = null;

  public BankServerInterfaceHolder ()
  {
  }

  public BankServerInterfaceHolder (common.BankServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.BankServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.BankServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.BankServerInterfaceHelper.type ();
  }

}
