package common;


/**
* common/BankServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bankserver.idl
* Thursday, November 2, 2017 1:04:54 PM EDT
*/


//Interface for the Banking Server
public interface BankServerInterface extends BankServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BankServerInterface
