package common;

/**
* common/BranchIDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bankserver.idl
* Wednesday, November 1, 2017 2:24:31 PM EDT
*/

public final class BranchIDHolder implements org.omg.CORBA.portable.Streamable
{
  public common.BranchID value = null;

  public BranchIDHolder ()
  {
  }

  public BranchIDHolder (common.BranchID initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.BranchIDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.BranchIDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.BranchIDHelper.type ();
  }

}
